#!/bin/bash
# Derives the two release PKGBUILDs from packaging/aur/PKGBUILD, which is the
# only hand-maintained one. The depends array used to exist in two places and
# had already drifted: the released source package was missing zlib, which the
# daemon links directly.
#
# plasma-lyrics is sed-derived so that build(), check() and package() stay
# single-sourced. plasma-lyrics-bin shares nothing but depends, so it is a
# template with that one array spliced in.
#
# Usage: generate.sh <version> <tag> <outdir>
#   Emits <outdir>/plasma-lyrics/PKGBUILD.
#   Call again with --bin once the payload tarball exists to emit
#   <outdir>/plasma-lyrics-bin/PKGBUILD.
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GIT_PKGBUILD="$HERE/PKGBUILD"
URL='https://github.com/swim233/plasma-lyrics'

# The array can wrap, so take everything from depends=( to the closing paren.
extract_depends() {
  sed -n '/^depends=(/,/)$/p' "$GIT_PKGBUILD"
}

gen_source() {
  local v=$1 tag=$2 out=$3 sum=$4
  mkdir -p "$out/plasma-lyrics"
  sed \
    -e 's/^pkgname=plasma-lyrics-git$/pkgname=plasma-lyrics/' \
    -e "s/^pkgver=.*/pkgver=$v/" \
    -e "s/^makedepends=('git' /makedepends=(/" \
    -e '/^provides=/d' \
    -e '/^conflicts=/d' \
    -e "s|^source=.*|source=(\"\$pkgname-\$pkgver.tar.gz::$URL/releases/download/$tag/plasma-lyrics-$v.tar.gz\")|" \
    -e "s/^sha256sums=.*/sha256sums=('$sum')/" \
    -e 's|^  cmake -S "$pkgname" -B build|  cmake -S "$pkgname-$pkgver" -B build|' \
    "$GIT_PKGBUILD" \
    | sed '/^pkgver() {$/,/^}$/d' \
    | cat -s > "$out/plasma-lyrics/PKGBUILD"
}

gen_bin() {
  local v=$1 tag=$2 out=$3 sum=$4
  mkdir -p "$out/plasma-lyrics-bin"
  {
    sed -n '1p' "$GIT_PKGBUILD"
    cat <<HEADER
pkgname=plasma-lyrics-bin
pkgver=$v
pkgrel=1
pkgdesc='Native synchronized desktop lyrics widget for Plasma 6 (prebuilt)'
arch=('x86_64')
url='$URL'
license=('GPL-2.0-only')
# Generated by packaging/aur/generate.sh -- depends is copied verbatim from
# packaging/aur/PKGBUILD. A prebuilt package saves the build, not one single
# runtime dependency, so this array has to stay identical to the source one.
HEADER
    extract_depends
    cat <<'FOOTER'
provides=("plasma-lyrics=$pkgver")
# plasma-lyrics-git provides plasma-lyrics, so pacman resolves this against it
# too; naming the -git package as well would be redundant.
conflicts=('plasma-lyrics')
# The payload is makepkg's own $pkgdir from the source package, already
# stripped. Without !strip an installing user whose makepkg.conf enables debug
# re-strips binaries that carry nothing and gets an empty -debug- package.
options=('!strip' '!debug')
FOOTER
    cat <<HEADER
source=("\$pkgname-\$pkgver.tar.gz::$URL/releases/download/$tag/plasma-lyrics-$v-x86_64-bin.tar.gz")
sha256sums=('$sum')
HEADER
    cat <<'FOOTER'

package() {
  cp -a usr "$pkgdir/"
}
FOOTER
  } > "$out/plasma-lyrics-bin/PKGBUILD"
}

case ${1:-} in
  --bin) shift; gen_bin "$1" "$2" "$3" "$4" ;;
  *)     gen_source "$1" "$2" "$3" "$4" ;;
esac
